
apiVersion: v1
kind: Config
clusters:
- name: k3s
  cluster:
    server: https://YOUR_INSTANCE_IP:53866
    insecure-skip-tls-verify: true
contexts:
- name: k3s
  context:
    cluster: k3s
    user: admin
current-context: k3s
users:
- name: admin
  user:
    token: admin-token
  